const data = {
  products: [
    {
      name: 'Pink Flower',
      slug: 'pink-flower',
      category: 'Colourful Flowers',
      image: '/images/pink-flower.png',
      price: 10.99,
      rating: 4.8,
      numReviews: 8,
      countInStock: 20,
      description: 'Perfect for every occasion',
    },
    {
      name: 'Sunflower',
      slug: 'sun-flower',
      category: 'Seasonal',
      image: '/images/sun-flower.png',
      price: 9.99,
      rating: 4.6,
      numReviews: 8,
      countInStock: 15,
      description: 'Plant me and watch how tall I grow!',
    },
    {
      name: 'Daisy Flower',
      slug: 'daisy-flower',
      category: 'Seasonal',
      image: '/images/daisy-flower.png',
      price: 8.99,
      rating: 4.5,
      numReviews: 7,
      countInStock: 16,
      description: 'Make me into a chain!',
    },
    {
      name: 'Mixed Autumn Flowers',
      slug: 'mixed-autumn-flower',
      category: 'Autumn',
      image: '/images/autumn-mixed-flower.png',
      price: 8.99,
      rating: 4.5,
      numReviews: 7,
      countInStock: 16,
      description: 'I look great next to a pumpkin!',
    },
    {
      name: 'Autumn Flowers',
      slug: 'autumn-flower',
      category: 'Autumn',
      image: '/images/autumn-flower.png',
      price: 7.99,
      rating: 4.6,
      numReviews: 7,
      countInStock: 16,
      description: 'I look great in the porch!',
    },
  ],
};
